#!/bin/bash
DIR="`dirname \"$0\"`"
PYTHONPATH=$DIR \
jupyter nbconvert --to html --output-dir ../html \
  --Exporter.preprocessors regexremove.MyRegexRemovePreprocessor  \
 '--MyRegexRemovePreprocessor.input=^# hide$' \
 '--MyRegexRemovePreprocessor.input=^# hideinput$' \
 '--MyRegexRemovePreprocessor.output=^# hideoutput$' \
 '--MyRegexRemovePreprocessor.all=^# hideall$' \
"$1"