#!/bin/bash
DIR="`dirname \"$0\"`"
PYTHONPATH=$DIR \
jupyter nbconvert --to pdf \
 --LatexExporter.template_paths $DIR/latex_config \
 --Exporter.preprocessors regexremove.MyRegexRemovePreprocessor  \
 '--MyRegexRemovePreprocessor.input=^# hide$' \
 '--MyRegexRemovePreprocessor.input=^# hideinput$' \
 '--MyRegexRemovePreprocessor.output=^# hideoutput$' \
 '--MyRegexRemovePreprocessor.all=^# hideall$' \
$1
# 

  